# This is a configuration file for the bacon tool

[jobs.reset-settings-and-run]
command = [
  "sh",
  "-c",
  "trash ~/.local/share/logviewer/app.ron; cargo run",
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
kill = ["pkill", "-TERM", "-P"]

[keybindings]
ctrl-d = "job:reset-settings-and-run"
